### ISSUE TITLE
can't start frontend container 

### ISSUE THREAD

**Issue by ricardo17coelho** [gsc2001/vuejs-template#1]
Error: `standard_init_linux.go:219: exec user process caused: no such file or directory`

OS: Windows 10

**Comment by ricardo17coelho** [comment]
Found fix [here](https://stackoverflow.com/questions/51508150/standard-init-linux-go190-exec-user-process-caused-no-such-file-or-directory)

**Comment by gsc2001** [comment]
Thanks for the heads up @ricardo17coelho , it was due to crlf line endings!
