### ISSUE TITLE
[Improvement] Vue3 support

### ISSUE THREAD

**Issue by Pk13055** [gsc2001/vuejs-template#2]
https://next.vuetifyjs.com/en/getting-started/installation/

**Comment by gsc2001** [comment]
Hey @Pk13055,

I am currently very busy managing a lot of stuff, therefore won't be able to work on this any time soon. But if you could raise a PR for the same, that would be great!

**Comment by Pk13055** [comment]
Sure, will look into it. I had started using Quasar instead since they already had vue3 support, but will look into this.
